// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TE.Data;

#nullable disable

namespace TE.Data.Migrations
{
    [DbContext(typeof(TEContext))]
    partial class TEContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TE.Core.Domain.Beneficiary", b =>
                {
                    b.Property<string>("CIN")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CIN");

                    b.ToTable("Beneficiary");
                });

            modelBuilder.Entity("TE.Core.Domain.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MyDonatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MyDonatorId");

                    b.ToTable("Donation");
                });

            modelBuilder.Entity("TE.Core.Domain.Donator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Donator");
                });

            modelBuilder.Entity("TE.Core.Domain.Kafala", b =>
                {
                    b.Property<string>("BeneficiaryFk")
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("DonatorFk")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BeneficiaryFk", "DonatorFk");

                    b.HasIndex("DonatorFk");

                    b.ToTable("Kafala");
                });

            modelBuilder.Entity("TE.Core.Domain.Beneficiary", b =>
                {
                    b.OwnsOne("TE.Core.Domain.Contact", "MyContact", b1 =>
                        {
                            b1.Property<string>("BeneficiaryCIN")
                                .HasColumnType("nvarchar(8)");

                            b1.Property<string>("Adress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BeneficiaryCIN");

                            b1.ToTable("Beneficiary");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryCIN");
                        });

                    b.Navigation("MyContact")
                        .IsRequired();
                });

            modelBuilder.Entity("TE.Core.Domain.Donation", b =>
                {
                    b.HasOne("TE.Core.Domain.Donator", "MyDonator")
                        .WithMany("Donations")
                        .HasForeignKey("MyDonatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyDonator");
                });

            modelBuilder.Entity("TE.Core.Domain.Donator", b =>
                {
                    b.OwnsOne("TE.Core.Domain.Contact", "MyContact", b1 =>
                        {
                            b1.Property<int>("DonatorId")
                                .HasColumnType("int");

                            b1.Property<string>("Adress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DonatorId");

                            b1.ToTable("Donator");

                            b1.WithOwner()
                                .HasForeignKey("DonatorId");
                        });

                    b.Navigation("MyContact")
                        .IsRequired();
                });

            modelBuilder.Entity("TE.Core.Domain.Kafala", b =>
                {
                    b.HasOne("TE.Core.Domain.Beneficiary", "MyBeneficiary")
                        .WithMany("Kafalas")
                        .HasForeignKey("BeneficiaryFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.Donator", "MYDonator")
                        .WithMany("Kafalas")
                        .HasForeignKey("DonatorFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MYDonator");

                    b.Navigation("MyBeneficiary");
                });

            modelBuilder.Entity("TE.Core.Domain.Beneficiary", b =>
                {
                    b.Navigation("Kafalas");
                });

            modelBuilder.Entity("TE.Core.Domain.Donator", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Kafalas");
                });
#pragma warning restore 612, 618
        }
    }
}
